Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/7/2022
Var
// Seção de Declarações das variáveis 
   a,b : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   a <- 7
   b <- 9
   escreva (a <=(b - 2))

Fimalgoritmo